version: '3'
services:
  gogs:
    image: gogs/gogs
    restart: always
    ports:
      - "10022:22"
      - "10080:3000"
    volumes:
      - gogs_data:/data
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    restart: 'always'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: awesome
      MYSQL_DATABASE: gogs
      MYSQL_USER: gogs
      MYSQL_PASSWORD: awesome
      TZ: America/Sao_Paulo

volumes:
  gogs_data:
  mysql_data: